import { Component } from '@angular/core';
import {Subpruebas} from './types/subpruebas';

@Component({
  selector: 'avz-wisc-iv',
  templateUrl: './wisc-iv.component.html',
  styleUrls: ['./wisc-iv.component.css']
})
export class WiscIvComponent {
  public condition = false;
  public pruebasWisc: Array<Subpruebas> = [
    {
      indice:'dc',
      nombre:'Diseño con cubos',
      escalarUno:'Escalar',
      escalarDos: 'Razonamiento perceptual',
      escalarTres:'Escala total',
      primero:true,
      segundo:false,
      tercero:true,
      cuarto:true,
    },
    {
      indice:'se',
      nombre:'Semejanzas',
      escalarUno:'Escalar',
      escalarDos: 'Comprensión verbal',
      escalarTres:'Escala total',
      primero:false,
      segundo:true,
      tercero:true,
      cuarto:true,
    },
    {
      indice:'rd',
      nombre:'Retención de dígitos',
      escalarUno:'Escalar',
      escalarDos: 'Memoria de trabajo',
      escalarTres:'Escala total',
      primero:true,
      segundo:true,
      tercero:false,
      cuarto:true,
    },
    {
      indice:'cd',
      nombre:'Conceptos con dibujos',
      escalarUno:'Escalar',
      escalarDos: 'Razonamiento perceptual',
      escalarTres:'Escala total',
      primero:true,
      segundo:false,
      tercero:true,
      cuarto:true,
    },
    {
      indice:'cl',
      nombre:'Claves',
      escalarUno:'Escalar',
      escalarDos: 'Velocidad de procesamiento',
      escalarTres:'Escala total',
      primero:true,
      segundo:true,
      tercero:true,
      cuarto:false,
    },
    {
      indice:'vb',
      nombre:'Vocabulario',
      escalarUno:'Escalar',
      escalarDos: 'Vocabulario',
      escalarTres:'Escala total',
      primero:false,
      segundo:true,
      tercero:true,
      cuarto:true,
    },
    {
      indice:'nl',
      nombre:'Sucesion de numeros y letras',
      escalarUno:'Escalar',
      escalarDos: 'Memoria de trabajo',
      escalarTres:'Escala total',
      primero:true,
      segundo:false,
      tercero:true,
      cuarto:false,
    },
    {
      indice:'mt',
      nombre:'Matrices',
      escalarUno:'Escalar',
      escalarDos: 'Razonamiento perceptual',
      escalarTres:'Escala total',
      primero:true,
      segundo:false,
      tercero:true,
      cuarto:true,
    },
    {
      indice:'cm',
      nombre:'Comprensión',
      escalarUno:'Escalar',
      escalarDos: 'Comprension verbal',
      escalarTres:'Escala total',
      primero:false,
      segundo:true,
      tercero:true,
      cuarto:true,
    },
    {
      indice:'bs',
      nombre:'Búsqueda de simbolos',
      escalarUno:'Escalar',
      escalarDos: 'Velocidad de procesamiento',
      escalarTres:'Escala total',
      primero:true,
      segundo:true,
      tercero:true,
      cuarto:false,
    }
  ];

  public alternasWisc: Array<Subpruebas> = [
    {
      indice:'fl',
      nombre:'(Figuras incompletas)',
      escalarUno:'Escalar',
      escalarDos: 'Razonamiento perceptual',
      escalarTres:'Escala total',
      primero:true,
      segundo:false,
      tercero:true,
      cuarto:false,
    },
    {
      indice:'rg',
      nombre:'(Registros)',
      escalarUno:'Escalar',
      escalarDos: 'Velocidad de procesamiento',
      escalarTres:'Escala total',
      primero:true,
      segundo:false,
      tercero:true,
      cuarto:false,
    },
    {
      indice:'inf',
      nombre:'(Información)',
      escalarUno:'Escalar',
      escalarDos: 'Comprensión verbal',
      escalarTres:'Escala total',
      primero:true,
      segundo:false,
      tercero:true,
      cuarto:false,
    },
    {
      indice:'ar',
      nombre:'(Aritmética)',
      escalarUno:'Escalar',
      escalarDos: 'Memoria de trabajo',
      escalarTres:'Escala total',
      primero:true,
      segundo:false,
      tercero:true,
      cuarto:false,
    },
    {
      indice:'pc',
      nombre:'Palabras en contexto(Pistas)',
      escalarUno:'Escalar',
      escalarDos: 'Comprension Verbal',
      escalarTres:'Escala total',
      primero:true,
      segundo:false,
      tercero:true,
      cuarto:false,
    }
  ];

}
